{% set name = "rasterio" %}
{% set version = "1.4.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/mapbox/{{ name }}/archive/{{ version }}.tar.gz
  sha256: 056bc5ad56600f27fbebdaec76ec8c1ff66f2adf6b54d33fabb816d1a9e914d5

build:
  number: 0
  skip: True  # [py<310]
  entry_points:
    - rio = rasterio.rio.main:main_group

requirements:
  build:
    - {{ stdlib("c") }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cython
    - numpy >=1.24
  host:
    - python
    - pip
    - cython
    - numpy >=1.24
    - libgdal-core
    - setuptools >=67.8
    - wheel
    - proj
  run:
    - python
    - affine
    - attrs
    - certifi
    - click >=4,!=8.2.* # https://github.com/pallets/click/issues/2939
    - click-plugins
    - cligj >=0.5
    - libgdal-core
    - numpy >=1.24
    - pyparsing
    - proj

{% set tests_to_skip = "_not_a_real_test" %}

# Skipping geolocation warp tests due to minor numerical variations in reprojected output.
{% set tests_to_skip = tests_to_skip + " or test_geoloc_warp_array" %}
{% set tests_to_skip = tests_to_skip + " or test_geoloc_warp_dataset" %}
{% set tests_to_skip = tests_to_skip + " or test_geoloc_warp_array_subsampled" %}

# E   FileExistsError: [WinError 183] Cannot create a file when that file already exists:
{% set tests_to_skip = tests_to_skip + " or test_decimated_no_use_overview" %}  # [win]

test:
  source_files:
    - tests
    # Needed to provide pytest markers
    - setup.cfg
  imports:
    - rasterio
    - rasterio.abc
    - rasterio.control
    - rasterio.coords
    - rasterio.crs
    - rasterio.drivers
    - rasterio.dtypes
    - rasterio.enums
    - rasterio.env
    - rasterio.errors
    - rasterio.features
    - rasterio.fill
    - rasterio.io
    - rasterio.mask
    - rasterio.merge
    - rasterio.plot
    - rasterio.profiles
    - rasterio.rio
    - rasterio.rpc
    - rasterio.serde
    - rasterio.session
    - rasterio.shutil
    - rasterio.stack
    - rasterio.transform
    - rasterio.vrt
    - rasterio.warp
    - rasterio.windows
  requires:
    - pip
    - pytest >=2.8.2
    - pytest-cov >=2.2.0
    - ipython>=2.0
    - boto3 >=1.2.4
    - fsspec
    - packaging
    - hypothesis
    - shapely
    - aiohttp

  files:
    - test_data/test.tif

  commands:
    - pip check
    - rio --help
    - rio info test_data/test.tif
    - python -m pytest -v -m "not wheel" -rxXs -k "not ({{ tests_to_skip }})" tests

about:
  home: https://github.com/mapbox/rasterio
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  description: |
     Rasterio reads and writes these formats and provides a Python API based on N-D arrays.
  summary: 'Rasterio reads and writes geospatial raster datasets'
  dev_url: https://github.com/mapbox/rasterio
  doc_url: https://rasterio.readthedocs.io

extra:
  recipe-maintainers:
    - ocefpaf
    - ceholden
    - snowman2
