{% set version = "0.36.0" %}

package:
  name: rasterio
  version: {{ version }}

source:
  git_url: https://github.com/mapbox/rasterio.git
  git_tag: {{ version }}

build:
  number: 2
  entry_points:
    - rio = rasterio.rio.main:main_group

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - setuptools
    - cython
    - numpy
    - libgdal
  run:
    - python
    - setuptools
    - {{ pin_compatible('numpy') }}
    - affine >=1.3.0
    - attrs
    - boto3 >=1.2.4
    - cligj
    - enum34  # [py27]
    - snuggs >=1.4.1
    - click-plugins

test:
  imports:
    - rasterio
  files:
    - test_data/test.tif
  commands:
    - rio --help
    - rio info $RECIPE_DIR/test_data/test.tif  # [not win]
    - rio info %RECIPE_DIR%\test_data\test.tif  # [win]

about:
  home: https://github.com/mapbox/rasterio
  license: BSD 3-Clause
  license_file: LICENSE.txt
  summary: 'Rasterio reads and writes geospatial raster datasets.'

extra:
  recipe-maintainers:
    - ocefpaf
    - ceholden
    - msarahan
