{% set name = "rasterio" %}
{% set version = "1.4.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/mapbox/{{ name }}/archive/{{ version }}.tar.gz
  sha256: 056bc5ad56600f27fbebdaec76ec8c1ff66f2adf6b54d33fabb816d1a9e914d5

build:
  number: 0
  skip: True  # [py<310]
  entry_points:
    - rio = rasterio.rio.main:main_group

requirements:
  build:
    - {{ stdlib("c") }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cython
    - numpy >=1.24
  host:
    - python
    - pip
    - cython
    - numpy >=1.24
    - libgdal-core
    - setuptools >=67.8
    # - wheel
    - proj
  run:
    - python
    - affine
    - attrs
    - certifi
    - click >=4,!=8.2.* # https://github.com/pallets/click/issues/2939
    - click-plugins
    - cligj >=0.5
    - libgdal-core
    - numpy >=1.24
    - pyparsing
    - proj

{% set tests_to_skip = "_not_a_real_test" %}

# Skipping geolocation warp tests due to minor numerical variations in reprojected output.
{% set tests_to_skip = tests_to_skip + " or test_geoloc_warp_array" %}
{% set tests_to_skip = tests_to_skip + " or test_geoloc_warp_dataset" %}
{% set tests_to_skip = tests_to_skip + " or test_geoloc_warp_array_subsampled" %}

# E   FileExistsError: [WinError 183] Cannot create a file when that file already exists:
{% set tests_to_skip = tests_to_skip + " or test_decimated_no_use_overview" %}  # [win]


# XFAIL tests/test_colorinterp.py::test_set_colorinterp_all[ColorInterp.gray0] - Setting colorinterp to gray fails with GDAL 2.3, see https://github.com/rasterio/rasterio/issues/1234
# XFAIL tests/test_env.py::test_aws_unsigned_subenv - Turning off signing in an inner env does not work in Rasterio 1.0
# XFAIL tests/test_features.py::test_rasterize_shapes_out_dtype_mismatch - shape values are always unsafely cast to the given dtype.
# XFAIL tests/test_filepath.py::test_vsifile_copyfiles - Copying is not supported by FilePath
# XFAIL tests/test_filepath.py::test_multi_vsifile - FilePath does not implement '.files' property properly.
# XFAIL tests/test_mask_creation.py::test_create_sidecar_mask - Internal mask are the default since 3.9.0.
# XFAIL tests/test_warp.py::test_target_aligned_pixels - Projection extents have changed with PROJ 8
# XFAIL tests/test_warp.py::test_resample_no_invert_proj[Resampling.bilinear] - Some resampling methods succeed but produce blank images. See https://github.com/rasterio/rasterio/issues/614
# {% set tests_to_skip = tests_to_skip + " or test_set_colorinterp_all" %}  # [linux]
# {% set tests_to_skip = tests_to_skip + " or test_aws_unsigned_subenv" %}  # [linux]
# {% set tests_to_skip = tests_to_skip + " or test_rasterize_shapes_out_dtype_mismatch" %}  # [linux]
# {% set tests_to_skip = tests_to_skip + " or test_vsifile_copyfiles" %}  # [linux]
# {% set tests_to_skip = tests_to_skip + " or test_multi_vsifile" %}  # [linux]
# {% set tests_to_skip = tests_to_skip + " or test_create_sidecar_mask" %}  # [linux]
# {% set tests_to_skip = tests_to_skip + " or test_target_aligned_pixels" %}  # [linux]
# {% set tests_to_skip = tests_to_skip + " or test_resample_no_invert_proj" %}  # [linux]


# test_s3_open_with_env 
# test_s3_open_with_implicit_env 
# test_s3_open_with_implicit_env_no_boto3 

# test_sharing_off 






test:
  source_files:
    - tests
    # Needed to provide pytest markers
    - setup.cfg
  imports:
    - rasterio
    - rasterio.abc
    - rasterio.control
    - rasterio.coords
    - rasterio.crs
    - rasterio.drivers
    - rasterio.dtypes
    - rasterio.enums
    - rasterio.env
    - rasterio.errors
    - rasterio.features
    - rasterio.fill
    - rasterio.io
    - rasterio.mask
    - rasterio.merge
    - rasterio.plot
    - rasterio.profiles
    - rasterio.rio
    - rasterio.rpc
    - rasterio.serde
    - rasterio.session
    - rasterio.shutil
    - rasterio.stack
    - rasterio.transform
    - rasterio.vrt
    - rasterio.warp
    - rasterio.windows
  requires:
    - pip
    - pytest >=2.8.2,<8
    - pytest-cov >=2.2.0
    - ipython >=2.0
    - aiohttp
    - boto3 >=1.2.4
    - fsspec
    - hypothesis
    - libgdal-netcdf
    - matplotlib-base
    - packaging
    - requests
    - shapely

  files:
    - test_data/test.tif

  commands:
    - pip check
    - rio --help
    - rio info test_data/test.tif   # [not win]
    - rio info test_data\\test.tif  # [win]
    - python -m pytest -v -m "not wheel" -rxXs -k "not ({{ tests_to_skip }})" tests

about:
  home: https://github.com/mapbox/rasterio
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  description: |
     Rasterio reads and writes these formats and provides a Python API based on N-D arrays.
  summary: 'Rasterio reads and writes geospatial raster datasets'
  dev_url: https://github.com/mapbox/rasterio
  doc_url: https://rasterio.readthedocs.io

extra:
  recipe-maintainers:
    - ocefpaf
    - ceholden
    - snowman2
