{% set version = "1.4.3" %}

package:
  name: rasterio
  version: {{ version }}

source:
  url: https://github.com/mapbox/rasterio/archive/{{ version }}.tar.gz
  sha256: dfa248fdc46f0e08ab957712b13a86d7cd49bce72f34b7fdca94af3b2d850181

build:
  number: 0
  skip: True  # [py<38 or s390x]
  entry_points:
    - rio = rasterio.rio.main:main_group

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - cython >=3.0.2,<3.1.0
    - numpy 2
    - libgdal
    - setuptools >=67.8
    - wheel
  run:
    - python
    - affine
    - attrs
    - certifi
    - click >=4.0
    - click-plugins
    - cligj >=0.5
    - libgdal
    - importlib-metadata  # [py<310]
    - numpy >=1.24
    - pyparsing

{% set tests_to_skip = "_not_a_real_test" %}

# Skipping geolocation warp tests due to minor numerical variations in reprojected output.
{% set tests_to_skip = tests_to_skip + " or test_geoloc_warp_array" %}
{% set tests_to_skip = tests_to_skip + " or test_geoloc_warp_dataset" %}
{% set tests_to_skip = tests_to_skip + " or test_geoloc_warp_array_subsampled" %}

# E   FileExistsError: [WinError 183] Cannot create a file when that file already exists:
{% set tests_to_skip = tests_to_skip + " or test_decimated_no_use_overview" %}  # [win]

test:
  source_files:
    - tests
    # Needed to provide pytest markers
    - setup.cfg
  imports:
    - rasterio
  requires:
    - pip
    - pytest >=2.8.2
    - pytest-cov >=2.2.0
    - ipython>=2.0
    - boto3 >=1.2.4
    - fsspec
    - packaging
    - hypothesis
    - shapely
    - aiohttp

  files:
    - test_data/test.tif

  commands:
    - pip check
    - rio --help
    - rio info {{ RECIPE_DIR }}/test_data/test.tif
    - python -m pytest -v -m "not wheel" -rxXs -k "not ({{ tests_to_skip }})" tests

about:
  home: https://github.com/mapbox/rasterio
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  description: |
     Rasterio reads and writes these formats and provides a Python API based on N-D arrays.
  summary: 'Rasterio reads and writes geospatial raster datasets'
  dev_url: https://github.com/mapbox/rasterio
  doc_url: https://rasterio.readthedocs.io

extra:
  recipe-maintainers:
    - ocefpaf
    - ceholden
    - snowman2
