{% set version = "1.3.10" %}

package:
  name: rasterio
  version: {{ version }}

source:
  url: https://github.com/mapbox/rasterio/archive/{{ version }}.tar.gz
  sha256: 0da4bea271a7f2ef2c44f528245a4f5c76ec635d075a0bd834300c75924b62c5

build:
  number: 0
  skip: True  # [py<38 or s390x]
  entry_points:
    - rio = rasterio.rio.main:main_group

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - cython ~=3.0.2
    - numpy
    - libgdal
    - setuptools
    - wheel
  run:
    - python
    - affine
    - attrs
    - certifi
    - click >=4.0
    - click-plugins
    - cligj >=0.5
    - libgdal
    - setuptools
    - snuggs >=1.4.1
    - importlib-metadata  # [py<310]
    - {{ pin_compatible('numpy') }}

test:
  source_files:
    - tests
  imports:
    - rasterio
  requires:
    - pip
    - pytest >=2.8.2
    - pytest-cov >=2.2.0
    - ipython>=2.0
    - boto3 >=1.3.1
    - matplotlib-base
    - packaging
    - hypothesis
    - shapely
    - pyparsing ~=3.1
  files:
    - test_data/test.tif
  commands:
    - pip check
    - rio --help
    - rio info {{ RECIPE_DIR }}/test_data/test.tif  # [not win]
    - rio info {{ RECIPE_DIR }}\\test_data\\test.tif  # [win]
    # test_target_aligned_pixels is failing for all OSes for proj 8.0.0
    # skip linux tests for cross-compiled targets
    - $PYTHON -m pytest -v -m "not wheel" -rxXs -k "not (test_target_aligned_pixels or test_info_azure_unsigned)" tests  # [linux and build_platform == target_platform]
    - $PYTHON -m pytest -v -m "not wheel" -rxXs -k "not (test_target_aligned_pixels or test_outer_boundless_pixel_fidelity or test_info_azure_unsigned)" tests  # [linux and build_platform == target_platform]
    - $PYTHON -m pytest -v -m "not wheel" -rxXs -k "not (test_target_aligned_pixels or test_reproject_error_propagation or test_outer_boundless_pixel_fidelity)" tests  # [osx]
    - python -m pytest -v -m "not wheel" -rxXs -k "not (test_hit_ovr or test_file_in_handler_with_vfs or test_files or test_parse_windows_path or test_copyfiles_same_dataset_another_name or test_context or test_target_aligned_pixels or test_decimated_no_use_overview or test_reproject_error_propagation)" tests  # [win]

about:
  home: https://github.com/mapbox/rasterio
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  description: |
     Rasterio reads and writes these formats and provides a Python API based on N-D arrays.
  summary: 'Rasterio reads and writes geospatial raster datasets'
  dev_url: https://github.com/mapbox/rasterio
  doc_url: https://rasterio.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - ocefpaf
    - ceholden
    - snowman2
