{% set version = "0.36.0" %}

package:
    name: rasterio
    version: {{ version }}

source:
    fn: rasterio-{{ version }}.tar.gz
    url: https://github.com/mapbox/rasterio/archive/{{ version }}.tar.gz
    sha256: 292d583dec745792242846081abc8c3a97a606af78f9fa3f655467b5b60a348a

build:
    number: 2
    entry_points:
        - rio = rasterio.rio.main:main_group

requirements:
    build:
        - python
        - numpy x.x
        - cython
        - setuptools
        - gdal 2.1.*
    run:
        - python
        - setuptools
        - affine
        - cligj
        - enum34  # [py27]
        - numpy x.x
        - snuggs
        - gdal 2.1.*
        - click-plugins

test:
    imports:
        - rasterio
    commands:
        - rio --help
        - conda inspect linkages -n _test rasterio  # [not win]

about:
    home: https://github.com/mapbox/rasterio
    license: BSD 3-Clause
    summary: 'Rasterio reads and writes geospatial raster datasets.'

extra:
    recipe-maintainers:
        - ocefpaf
        - ceholden
