{% set version = "1.0.5" %}

package:
  name: rasterio
  version: {{ version }}

source:
  url: https://github.com/mapbox/rasterio/archive/{{ version }}.tar.gz
  sha256: 83042795e65229021a8395551eb9085a954559d55a98d85864f9a078f0da1ff4

build:
  number: 0
  entry_points:
    - rio = rasterio.rio.main:main_group

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - cython
    - numpy
    - libgdal
  run:
    - python
    - setuptools
    - libgdal
    - affine
    - attrs
    - cligj
    - {{ pin_compatible('numpy') }}
    - snuggs >=1.4.1
    - click-plugins
    # Extras.
    - enum34  # [py27]
    - boto3 >=1.2.4
test:
  source_files:
    - tests
  imports:
    - rasterio
  requires:
    - packaging
    - hypothesis
    - pytest >=2.8.2
    - pytest-cov >=2.2.0
  files:
    - test_data/test.tif
  commands:
    - rio --help
    - rio info $RECIPE_DIR/test_data/test.tif  # [not win]
    - rio info %RECIPE_DIR%\test_data\test.tif  # [win]
    # Skipping some tests due to `fixture 'caplog' not found` or `access_key`.
    - pytest -s -rxs -v -k "not (test_warped_vrt_msk_add_alpha or test_warped_vrt_msk_nodata or test_open_https_vsicurl or test_requester_pays)" tests  # [not win]

about:
  home: https://github.com/mapbox/rasterio
  license: BSD 3-Clause
  license_file: LICENSE.txt
  summary: 'Rasterio reads and writes geospatial raster datasets'

extra:
  recipe-maintainers:
    - ocefpaf
    - ceholden
    - snowman2
