{% set version = "0.35.0.post1" %}

package:
    name: rasterio
    version: {{ version }}

source:
    fn: rasterio-{{ version }}.tar.gz
    url: https://github.com/mapbox/rasterio/archive/{{ version }}.tar.gz
    sha256: c078b1d0950be212607918d67234d4134e392ecf09615525825ec25f6a16989f

build:
    number: 0
    entry_points:
        - rio = rasterio.rio.main:main_group

requirements:
    build:
        - python
        - numpy x.x
        - cython
        - setuptools
        # Rasterio **does** work with gdal, this is just b/c rasterio is usually installed along side fiona.
        - gdal 1.11.4
    run:
        - python
        - affine
        - cligj
        - enum34  # [py27]
        - numpy x.x
        - snuggs
        - gdal 1.11.4
        - click-plugins

test:
    imports:
        - rasterio
    commands:
        - rio --help

about:
    home: https://github.com/mapbox/rasterio
    license: BSD 3-Clause
    summary: Rasterio reads and writes geospatial raster datasets

extra:
    recipe-maintainers:
        - ocefpaf
        - ceholden
