{% set version = "1.2.10" %}

package:
  name: rasterio
  version: {{ version }}

source:
  url: https://github.com/mapbox/rasterio/archive/{{ version }}.tar.gz
  sha256: f9df8548e8a053d5db6057a4fd28d940d98a06d249f8af9e8fde1d8e9587d0b5

build:
  number: 1
  skip: True  # [py<36 or s390x]
  entry_points:
    - rio = rasterio.rio.main:main_group

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - cython
    - numpy
    - libgdal
    - setuptools
    - wheel
  run:
    - python

    - affine
    - attrs
    - certifi
    - click >=4.0
    - click-plugins
    - cligj >=0.5
    - libgdal
    - setuptools
    - snuggs >=1.4.1
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - rasterio
  requires:
    - pip
    - pytest >=2.8.2
    - pytest-cov >=2.2.0
    - ipython>=2.0
    - boto3 >=1.2.4
    - matplotlib-base
    - packaging
    - hypothesis
    - shapely
  files:
    - test_data/test.tif
  commands:
    - pip check
    - rio --help
    - rio info {{ RECIPE_DIR }}/test_data/test.tif  # [not win]
    - rio info {{ RECIPE_DIR }}\\test_data\\test.tif  # [win]
    # 2022/4/25: Skip pytest because source files are large than 14Mb.
    # test_target_aligned_pixels is failing for all OSes for proj 8.0.0
    # skip linux tests for cross-compiled targets
    #- $PYTHON -m pytest -v -m "not wheel" -rxXs -k "not (test_target_aligned_pixels or test_info_azure_unsigned)" tests  # [linux and build_platform == target_platform]
    #- $PYTHON -m pytest -v -m "not wheel" -rxXs -k "not (test_target_aligned_pixels or test_outer_boundless_pixel_fidelity or test_info_azure_unsigned)" tests  # [linux and build_platform == target_platform]
    #- $PYTHON -m pytest -v -m "not wheel" -rxXs -k "not (test_target_aligned_pixels or test_reproject_error_propagation or test_outer_boundless_pixel_fidelity)" tests  # [osx]
    #- python -m pytest -v -m "not wheel" -rxXs -k "not (test_hit_ovr or test_file_in_handler_with_vfs or test_files or test_parse_windows_path or test_copyfiles_same_dataset_another_name or test_context or test_target_aligned_pixels or test_decimated_no_use_overview or test_reproject_error_propagation)" tests  # [win]

about:
  home: https://github.com/mapbox/rasterio
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: 'Rasterio reads and writes geospatial raster datasets'
  dev_url: https://github.com/mapbox/rasterio
  doc_url: https://rasterio.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - ocefpaf
    - ceholden
    - snowman2
