{% set version = "1.0a4" %}

package:
  name: rasterio
  version: {{ version }}

source:
  fn: rasterio-{{ version }}.tar.gz
  url: https://github.com/mapbox/rasterio/archive/{{ version }}.tar.gz
  sha256: f81fb7f8a76b6204f58fc589e478b6fc5247974f9410775e0405bd12bcf9904b

build:
  number: 0
  entry_points:
    - rio = rasterio.rio.main:main_group

requirements:
  build:
    - python
    - numpy x.x
    - cython
    - setuptools
    - gdal 2.1.*
  run:
    - python
    - setuptools
    - affine >=1.3.0
    - boto3 >=1.2.4
    - cligj
    - enum34  # [py27]
    - numpy x.x
    - snuggs >=1.2
    - gdal 2.1.*
    - click-plugins

test:
  imports:
    - rasterio
  files:
    - test_data/test.tif
  commands:
    - rio --help
    - rio info $RECIPE_DIR/test_data/test.tif  # [not win]
    - rio info %RECIPE_DIR%\test_data\test.tif  # [win]
    #- conda inspect linkages -p $PREFIX rasterio  # [not win]
    #- conda inspect objects -p $PREFIX rasterio  # [osx]

about:
  home: https://github.com/mapbox/rasterio
  license: BSD 3-Clause
  summary: 'Rasterio reads and writes geospatial raster datasets.'

extra:
  recipe-maintainers:
    - ocefpaf
    - ceholden
