{% set version = "0.36.0" %}

package:
  name: rasterio
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/r/rasterio/rasterio-{{ version }}.tar.gz
  sha256: 467d9cf8297a6912b33dde49fa519346ba766972344fbafb22f3dfc54225f08a

build:
  number: 2
  entry_points:
    - rio = rasterio.rio.main:main_group

requirements:
  build:
    - python
    - setuptools
    - cython
    - numpy 1.9.*  # [not (win and py36)]
    - numpy 1.11.*  # [win and py36]
    - gdal 2.1.*
  run:
    - python
    - setuptools
    - numpy >=1.9  # [not (win and py36)]
    - numpy >=1.11  # [win and py36]
    - affine >=1.3.0
    - attrs
    - boto3 >=1.2.4
    - cligj
    - enum34  # [py27]
    - snuggs >=1.4.1
    - gdal 2.1.*
    - click-plugins

test:
  imports:
    - rasterio
  files:
    - test_data/test.tif
  commands:
    - rio --help
    - rio info $RECIPE_DIR/test_data/test.tif  # [not win]
    - rio info %RECIPE_DIR%\test_data\test.tif  # [win]
    - conda inspect linkages -p $PREFIX $PKG_NAME  # [not win]
    - conda inspect objects -p $PREFIX $PKG_NAME  # [osx]

about:
  home: https://github.com/mapbox/rasterio
  license: BSD 3-Clause
  license_file: LICENSE.txt
  summary: 'Rasterio reads and writes geospatial raster datasets.'

extra:
  recipe-maintainers:
    - ocefpaf
    - ceholden
