{% set version = "0.35.1" %}

package:
    name: rasterio
    version: {{ version }}

source:
    fn: rasterio-{{ version }}.tar.gz
    url: https://github.com/mapbox/rasterio/archive/{{ version }}.tar.gz
    sha256: 2e4b94de3cf92f5d81de6d1265b45afd9ac3085b158dcfcaec47c39cfa66029a

build:
    number: 1
    entry_points:
        - rio = rasterio.rio.main:main_group

requirements:
    build:
        - python
        - numpy x.x
        - cython
        - setuptools
        # Rasterio **does** work with gdal, this is just b/c rasterio is usually installed along side fiona.
        - gdal 1.11.4
    run:
        - python
        - affine
        - cligj
        - enum34  # [py27]
        - numpy x.x
        - snuggs
        - gdal 1.11.4
        - click-plugins

test:
    imports:
        - rasterio
    commands:
        - rio --help
        - conda inspect linkages -n _test rasterio  # [linux]

about:
    home: https://github.com/mapbox/rasterio
    license: BSD 3-Clause
    summary: Rasterio reads and writes geospatial raster datasets

extra:
    recipe-maintainers:
        - ocefpaf
        - ceholden
