{% set version = "1.0.21" %}

package:
  name: rasterio
  version: {{ version }}

source:
  url: https://github.com/mapbox/rasterio/archive/{{ version }}.tar.gz
  sha256: cbe1dd5a4bf12bb2f039480ad1b6a44d7324e956212ae0c5fd93604390fb7faa

build:
  number: 1
  skip: True  # [win and py27]
  entry_points:
    - rio = rasterio.rio.main:main_group

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - cython
    - numpy
    - libgdal
  run:
    - python
    - setuptools >=0.9.8
    - libgdal
    - affine >=1.3.0
    - attrs >=16.0.0
    - click >=4,<8
    - cligj >=0.5
    - {{ pin_compatible('numpy') }}
    - snuggs >=1.4.1
    - click-plugins
    - enum34  # [py<34]
test:
  source_files:
    - tests
  imports:
    - rasterio
  requires:
    - pytest >=2.8.2
    - pytest-cov >=2.2.0
    - boto3 >=1.2.4
    - packaging
    - hypothesis
    - mock  # [py2k]
    - futures  # [py2k]
  files:
    - test_data/test.tif
  commands:
    - rio --help
    - rio info $RECIPE_DIR/test_data/test.tif  # [not win]
    - rio info %RECIPE_DIR%\test_data\test.tif  # [win]
    # Skipping some tests due to `fixture 'caplog' not found` or `access_key`.
    - pytest -s -rxs -v -m "not wheel" -k "not (test_warped_vrt_msk_add_alpha or test_warped_vrt_msk_nodata or test_open_https_vsicurl or test_requester_pays or test_ensure_env_decorator_sets_gdal_data_prefix)" tests  # [not win]

about:
  home: https://github.com/mapbox/rasterio
  license: BSD 3-Clause
  license_file: LICENSE.txt
  summary: 'Rasterio reads and writes geospatial raster datasets'

extra:
  recipe-maintainers:
    - ocefpaf
    - ceholden
    - snowman2
